extends RefCounted

## Handles per-frame wave spawn logic. Reads the current_wave from main
## (which was generated by WaveFormula) and spawns enemies accordingly.

var main: Node


func _init(main_node: Node) -> void:
	main = main_node


func update_spawning(delta: float, spawn_boss_callable: Callable) -> void:
	var wave: Dictionary = main.current_wave
	main.spawn_timer += delta * main._test_scale("wave_scale")
	if wave.get("is_boss_wave", false):
		_update_boss_wave(wave, spawn_boss_callable)
		return
	if main.spawn_timer < float(wave.get("spawn_interval", 1.0)):
		return
	main.spawn_timer = 0.0
	var composition: Array = wave.get("composition", ["grunt"])
	if composition.is_empty():
		return
	var enemy_type: String = composition[randi() % composition.size()]
	main.enemies_ai.spawn_enemy(main.actor_root, main.enemies, enemy_type,
			float(wave.get("hp_scale", 1.0)), main.enemy_defs, main.config)


func _update_boss_wave(wave: Dictionary, spawn_boss_callable: Callable) -> void:
	if main.boss_ref.is_empty():
		spawn_boss_callable.call(float(wave.get("boss_hp_scale", 1.0)))
	var minion_interval := float(wave.get("minion_interval", 2.0))
	if minion_interval <= 0.0:
		return
	if main.spawn_timer < minion_interval:
		return
	main.spawn_timer = 0.0
	var minions: Array = wave.get("minion_types", [])
	if minions.is_empty():
		return
	var enemy_type: String = minions[randi() % minions.size()]
	main.enemies_ai.spawn_enemy(main.actor_root, main.enemies, enemy_type,
			float(wave.get("hp_scale", 1.0)), main.enemy_defs, main.config)
