extends GdUnitTestSuite

## Tests for the critical hit system wired through combat_resolver.gd.
## crit_chance is generated by gear (Razor/of Precision) and consumed here.

const CombatResolver := preload("res://scripts/combat_resolver.gd")
const MaterialFactory := preload("res://scripts/material_factory.gd")
const PixelArtRenderer := preload("res://scripts/pixel_art_renderer.gd")
const DamageNumbers := preload("res://scripts/damage_numbers.gd")


class SpyDamageNumbers:
	extends RefCounted
	var last_amount: float = 0.0
	var last_is_crit: bool = false
	func spawn(_root: Node3D, _pos: Vector3, amount: float, _color: Color, is_crit: bool = false, _id: int = -1) -> void:
		last_amount = amount
		last_is_crit = is_crit


func _make_combat() -> CombatResolver:
	return CombatResolver.new(MaterialFactory.new(), PixelArtRenderer.new())


func _make_enemy(pos: Vector3) -> Dictionary:
	var node := Node3D.new()
	node.position = pos
	node.scale = Vector3.ONE
	add_child(node)
	return {
		"id": "grunt", "node": node, "hp": 100.0, "max_hp": 100.0,
		"color": Color("ff0000"), "speed": 3.0, "contact_damage": 1.0,
		"attack_timer": 0.0, "behavior_timer": 0.0,
		"behavior_state": "chase", "enemy_uid": 1, "drop_xp": 1,
	}


func _make_projectile_root() -> Node3D:
	var root := Node3D.new()
	add_child(root)
	return root


# --- spawn_projectile stores crit_chance ---

func test_projectile_stores_crit_chance() -> void:
	var combat := _make_combat()
	var root := _make_projectile_root()
	var projectiles: Array = []
	combat.spawn_projectile(root, projectiles, Vector3.ZERO, Vector3(1, 0, 0),
		false, 10.0, 1, 20.0, 0.3, Color("ffffff"), null, null, 0.25)
	assert_int(projectiles.size()).is_equal(1)
	assert_float(float(projectiles[0]["crit_chance"])).is_equal_approx(0.25, 0.001)


func test_hostile_projectile_zero_crit_chance_by_default() -> void:
	var combat := _make_combat()
	var root := _make_projectile_root()
	var projectiles: Array = []
	combat.spawn_projectile(root, projectiles, Vector3.ZERO, Vector3(1, 0, 0),
		true, 5.0, 1, 15.0, 0.3, Color("ff617e"))
	assert_float(float(projectiles[0].get("crit_chance", 0.0))).is_equal_approx(0.0, 0.001)


# --- guaranteed crit deals double damage ---

func _run_projectile_hit(crit_chance: float, base_damage: float) -> Dictionary:
	var combat := _make_combat()
	var proj_root := _make_projectile_root()
	var fx_root := Node3D.new()
	add_child(fx_root)
	var spy := SpyDamageNumbers.new()
	var projectiles: Array = []
	# Spawn directly at enemy position so it hits immediately on first tick.
	var enemy := _make_enemy(Vector3(0, 0.58, 0))
	combat.spawn_projectile(proj_root, projectiles, Vector3(0, 0.58, 0),
		Vector3(1, 0, 0), false, base_damage, 10, 20.0, 0.3, Color("ffffff"), null, null, crit_chance)
	var enemies := [enemy]
	combat.update_projectiles(0.016, projectiles, enemies, {}, null, [], null, null,
		Callable(), Callable(), Callable(), fx_root, [], spy)
	return {"enemy_hp": float(enemies[0]["hp"]) if enemies.size() > 0 else -1.0, "spy": spy}


func test_100pct_crit_chance_doubles_damage() -> void:
	# With 100% crit chance, every hit must deal 2× base damage.
	var result := _run_projectile_hit(1.0, 20.0)
	# enemy started at 100 hp, 40 damage → 60 hp
	assert_float(result["enemy_hp"]).is_equal_approx(60.0, 0.01)
	assert_bool(result["spy"].last_is_crit).is_true()
	assert_float(result["spy"].last_amount).is_equal_approx(40.0, 0.01)


func test_0pct_crit_chance_deals_base_damage() -> void:
	var result := _run_projectile_hit(0.0, 20.0)
	# 20 damage only
	assert_float(result["enemy_hp"]).is_equal_approx(80.0, 0.01)
	assert_bool(result["spy"].last_is_crit).is_false()
	assert_float(result["spy"].last_amount).is_equal_approx(20.0, 0.01)


# --- crit_chance is additive from gear ---

func test_gear_system_accumulates_crit_chance() -> void:
	var gs := GearSystem.new()
	gs.equip({"id": "a", "name": "Razor Bow", "slot": "weapon_mod", "rarity": 1,
		"stats": {"crit_chance": 0.08}, "flavor": "Sharp."})
	var base := {"crit_chance": 0.0}
	var result := gs.apply_modifiers(base)
	assert_float(float(result["crit_chance"])).is_equal_approx(0.08, 0.001)


func test_two_crit_gear_stack_additively() -> void:
	var gs := GearSystem.new()
	gs.equip({"id": "a", "name": "Razor Bow", "slot": "weapon_mod", "rarity": 1,
		"stats": {"crit_chance": 0.08}, "flavor": "Sharp."})
	gs.equip({"id": "b", "name": "Bow of Precision", "slot": "bow_accessory", "rarity": 2,
		"stats": {"crit_chance": 0.06}, "flavor": "Precise."})
	var result := gs.apply_modifiers({"crit_chance": 0.0})
	assert_float(float(result["crit_chance"])).is_equal_approx(0.14, 0.001)
